package com.example.languageupx002;

import static com.example.languageupx002.Table.flag1;
import static com.example.languageupx002.Table.flag3;
import static com.example.languageupx002.Table.lang;
import static com.example.languageupx002.Table.langw;
import static com.example.languageupx002.Table.langtr;

import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.widget.Button;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.concurrent.atomic.AtomicInteger;

public class Welcome extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.welcome);
        this.getSupportActionBar().hide();
        final Button langwb1 = findViewById(R.id.button14);
        final Button langwb2 = findViewById(R.id.button39);
        final Button langwb3 = findViewById(R.id.button41);
        final Button langwb4 = findViewById(R.id.button16);
        final Button langwb5 = findViewById(R.id.button54);
        final Button langwb6 = findViewById(R.id.button59);
        final Button langwb7 = findViewById(R.id.button51);
        final Button langwb8 = findViewById(R.id.button56);
        final Button langwb9 = findViewById(R.id.button64);
        final Button langwb10 = findViewById(R.id.button69);
        final Button langwb11 = findViewById(R.id.button61);
        final Button langwb12 = findViewById(R.id.button66);
        final Button langtrb1 = findViewById(R.id.button114);
        final Button langtrb2 = findViewById(R.id.button139);
        final Button langtrb3 = findViewById(R.id.button141);
        final Button langtrb4 = findViewById(R.id.button116);
        final Button langtrb5 = findViewById(R.id.button154);
        final Button langtrb6 = findViewById(R.id.button159);
        final Button langtrb7 = findViewById(R.id.button151);
        final Button langtrb8 = findViewById(R.id.button156);
        final Button langtrb9 = findViewById(R.id.button164);
        final Button langtrb10 = findViewById(R.id.button169);
        final Button langtrb11 = findViewById(R.id.button161);
        final Button langtrb12 = findViewById(R.id.button166);
        final Button start = findViewById(R.id.button42);
        langwb1.setText("English\uD83C\uDDEC\uD83C\uDDE7");
        langwb2.setText("Français\uD83C\uDDEB\uD83C\uDDF7");
        langwb3.setText("Español\uD83C\uDDEA\uD83C\uDDF8");
        langwb4.setText("Português\uD83C\uDDF5\uD83C\uDDF9");
        langwb5.setText("Italiano\uD83C\uDDEE\uD83C\uDDF9");
        langwb6.setText("Deutsch\uD83C\uDDE9\uD83C\uDDEA");
        langwb7.setText("Русский\uD83C\uDDF7\uD83C\uDDFA");
        langwb8.setText("中文\uD83C\uDDE8\uD83C\uDDF3");
        langwb9.setText("한국어\uD83C\uDDF0\uD83C\uDDF7");
        langwb10.setText("日本語\uD83C\uDDEF\uD83C\uDDF5");
        langwb11.setText("हिन्दी\uD83C\uDDEE\uD83C\uDDF3");
        langwb12.setText("\uD83C\uDDE6\uD83C\uDDEAالعربية");
        langtrb1.setText("English\uD83C\uDDEC\uD83C\uDDE7");
        langtrb2.setText("Français\uD83C\uDDEB\uD83C\uDDF7");
        langtrb3.setText("Español\uD83C\uDDEA\uD83C\uDDF8");
        langtrb4.setText("Português\uD83C\uDDF5\uD83C\uDDF9");
        langtrb5.setText("Italiano\uD83C\uDDEE\uD83C\uDDF9");
        langtrb6.setText("Deutsch\uD83C\uDDE9\uD83C\uDDEA");
        langtrb7.setText("Русский\uD83C\uDDF7\uD83C\uDDFA");
        langtrb8.setText("中文\uD83C\uDDE8\uD83C\uDDF3");
        langtrb9.setText("한국어\uD83C\uDDF0\uD83C\uDDF7");
        langtrb10.setText("日本語\uD83C\uDDEF\uD83C\uDDF5");
        langtrb11.setText("हिन्दी\uD83C\uDDEE\uD83C\uDDF3");
        langtrb12.setText("\uD83C\uDDE6\uD83C\uDDEAالعربية");
        Toast toast = Toast.makeText(getApplicationContext(),
                "Change learning language/native language", Toast.LENGTH_SHORT);
        Toast finalToast = toast;
        start.setOnClickListener((v) -> {
            if(flag1 == 1 & flag3 == 1) {
                lang = langtr;
                try {
                    Intent intent = new Intent(Welcome.this, MainMenu.class);
                    startActivity(intent);
                    finish();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }else{
                finalToast.show();
            }
        });
        langwb1.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 1;
            flag1 = 1;
        });
        langwb2.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 2;
            flag1 = 1;
        });
        langwb3.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 3;
            flag1 = 1;
        });
        langwb4.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 4;
            flag1 = 1;
        });
        langwb5.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 5;
            flag1 = 1;
        });
        langwb6.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 6;
            flag1 = 1;
        });
        langwb7.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 7;
            flag1 = 1;
        });
        langwb8.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 8;
            flag1 = 1;
        });
        langwb9.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 9;
            flag1 = 1;
        });
        langwb10.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 10;
            flag1 = 1;
        });
        langwb11.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#00ff00"));
            langwb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langw = 11;
            flag1 = 1;
        });
        langwb12.setOnClickListener((v) -> {
            langwb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langwb12.setBackgroundColor(Color.parseColor("#00ff00"));
            langw = 12;
            flag1 = 1;
        });
        langtrb1.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 1;
            flag3 = 1;
        });
        langtrb2.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 2;
            flag3 = 1;
        });
        langtrb3.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 3;
            flag3 = 1;
        });
        langtrb4.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 4;
            flag3 = 1;
        });
        langtrb5.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 5;
            flag3 = 1;
        });
        langtrb6.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 6;
            flag3 = 1;
        });
        langtrb7.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 7;
            flag3 = 1;
        });
        langtrb8.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 8;
            flag3 = 1;
        });
        langtrb9.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 9;
            flag3 = 1;
        });
        langtrb10.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 10;
            flag3 = 1;
        });
        langtrb11.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#00ff00"));
            langtrb12.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtr = 11;
            flag3 = 1;
        });
        langtrb12.setOnClickListener((v) -> {
            langtrb1.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb2.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb3.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb4.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb5.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb6.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb7.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb8.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb9.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb10.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb11.setBackgroundColor(Color.parseColor("#a9a9a9"));
            langtrb12.setBackgroundColor(Color.parseColor("#00ff00"));
            langtr = 12;
            flag3 = 1;
        });
    }
}
